export type ImageNames =
  | "AuthBackground"
  | "actionCenter"
  | "agents"
  | "dashboard"
  | "Download"
  | "Edit"
  | "history"
  | "LogOut"
  | "Menu"
  | "Panoptimize White"
  | "Panoptimize"
  | "PanoptimizeApp Transparent"
  | "PanotpimizeApp"
  | "Settings"
  | "Toretto"
  | "X"
  | "Bell";
